version: '2'
services:
  app:
    image: ekaterinach/testv7
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres
  mypostgres:
    image: ekaterinach/postgrev8
    ports:
        - "5432:5432"